name: windows

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ./examples
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A"x64" -G"Visual Studio 17 2022"

    - name: Build
      working-directory: ./examples
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run test
      run: ${{github.workspace}}/build/Release/main.exe ${{github.workspace}}/examples/models/cnn_227_160_quantized.tflite

    - name: Upload files (Release) 
      uses: actions/upload-artifact@v3
      with:
        name: examples
        path: ${{github.workspace}}/build/Release